name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  **See changes**: https://github.com/Nr18/report2junit/compare/v$RESOLVED_VERSION...$PREVIOUS_TAG

categories:
  - title: '⚠️ Breaking'
    label:
      - 'breaking'
  - title: '🚀 Features'
    label:
      - 'feature'
  - title: '🐛 Bug Fixes'
    label:
      - 'bug'
  - title: '🧰 Maintenance'
    label:
      - 'maintenance'
  - title: '📚 Documentation'
    label:
      - 'docs'
  - title: 'Dependency Updates'
    label:
      - 'dependencies'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
      - 'maintenance'
      - 'docs'
      - 'dependencies'
      - 'security'

autolabeler:
  - label: 'chore'
    files:
      - '*.md'
    branch:
      - '/docs\/.+/'
      - '/chore\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
  - label: 'feature'
    branch:
      - '/feat\/.+/'

exclude-labels:
  - 'skip-changelog'
